let data = [
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/kyazotklprl8in3rlzmf",
    rtname: "Arbain Mandi",
    Ratings: 4.5,
    time: "30-35 min",
    menu: "North indian biryani",
    location: "Phaltan",
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/ghlqqsuu7ovhuzq8txgu",
    rtname: "Pind Punjabi",
    Ratings: 4.0,
    time: "30-35 min",
    menu: "Punjabi,north indian",
    location: "Baramati",
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/pxkczssapfhhd8w3b9jd",
    rtname: "Punjabi Treat",
    Ratings: 3.5,
    time: "30-35 min",
    menu: "Chainese North Indian",
    location: "Phaltan",
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/tsw3vukgewwlhmqni762",
    rtname: "Godavari Ruchulu",
    Ratings: 2.8,
    time: "30-35 min",
    menu: "Sauth indian biryani",
    location: "Baramati",
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/rb7lzh9ivotudnzr9rct",
    rtname: "Hotel Chaitantya",
    Ratings: 3.2,
    time: "30-35 min",
    menu: "Maharashtrian Chainese",
    location: "Baramati",
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/d2b39bda3a57f79ddf74dc0a2f4eb37c",
    rtname: "Biryani Zone",
    Ratings: 4.5,
    time: "30-35 min",
    menu: "Biryani",
    location: "Phaltan",
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/wkmehhokjp57lup8ij1s",
    rtname: "Biryani By KG",
    Ratings: 3.4,
    time: "30-35 min",
    menu: "North indian Hydrabadi biryani",
    location: "Baramati",
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/wkmehhokjp57lup8ij1s",
    rtname: "Behrouz Biryani",
    Ratings: 2.5,
    time: "30-35 min",
    menu: "North indian biryani kababs",
    location: "Baramati",
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/k5jwalqkha9t1czl0cc7",
    rtname: "Aroma Tandoor & Biryani",
    Ratings: 4.1,
    time: "30-35 min",
    menu: "indian biryani",
    location: "Phaltan",
  },
  {
    img: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/qfcxq8z12q07krpz25ec",
    rtname: "Tandoor Point",
    Ratings: 3.1,
    time: "30-35 min",
    menu: "Tandoor",
    location: "Phaltan",
  },
];

export default data;
